import { Router } from 'express';
import { auth } from '../middleware/auth.js';
import { isAdmin } from '../middleware/admin.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import * as c from '../controllers/adminController.js';
const router = Router();
router.use(auth, asyncHandler(isAdmin));
router.get('/stats', asyncHandler(c.stats));
router.get('/users', asyncHandler(c.listUsers));
router.get('/quiz', asyncHandler(c.listQuizAdmin));
router.post('/quiz', asyncHandler(c.createQuizAdmin));
router.put('/quiz/:id', asyncHandler(c.updateQuizAdmin));
router.delete('/quiz/:id', asyncHandler(c.deleteQuizAdmin));
router.get('/notes', asyncHandler(c.listNotesAdmin));
router.get('/community', asyncHandler(c.listCommunityAdmin));
router.get('/reports', asyncHandler(c.listReportsAdmin));
router.put('/reports/:id', asyncHandler(c.updateReportAdmin));
router.get('/catalog', asyncHandler(c.getAdminCatalog));
router.post('/catalog', asyncHandler(c.createCatalog));
router.put('/catalog/:id', asyncHandler(c.updateCatalog));
router.delete('/catalog/:id', asyncHandler(c.deleteCatalog));
router.get('/materials/:courseId', asyncHandler(c.getMaterials));
router.post('/materials', asyncHandler(c.createMaterial));
router.put('/materials/:id', asyncHandler(c.updateMaterial));
router.delete('/materials/:id', asyncHandler(c.deleteMaterial));
export default router;
