import { Router } from 'express';
import authRoutes from './authRoutes.js';
import profileRoutes from './profileRoutes.js';
import majorRoutes from './majorRoutes.js';
import catalogRoutes from './catalogRoutes.js';
import courseRoutes from './courseRoutes.js';
import eventRoutes from './eventRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import materialRoutes from './materialRoutes.js';
import roomRoutes from './roomRoutes.js';
import inviteRoutes from './inviteRoutes.js';
import chatRoutes from './chatRoutes.js';
import aiRoutes from './aiRoutes.js';
import dashboardRoutes from './dashboardRoutes.js';
import quizRoutes from './quizRoutes.js';
import adminRoutes from './adminRoutes.js';
import noteRoutes from './noteRoutes.js';
import resourceRoutes from './resourceRoutes.js';
import progressRoutes from './progressRoutes.js';
import communityRoutes from './communityRoutes.js';
import analyticsRoutes from './analyticsRoutes.js';
import gamificationRoutes from './gamificationRoutes.js';
import reportRoutes from './reportRoutes.js';

const router = Router();

router.get('/health', (_req, res) => res.json({ ok: true, service: 'StudyBuddy API', architecture: 'routes/controllers/prisma' }));
router.use('/auth', authRoutes);
router.use('/profile', profileRoutes);
router.use('/majors', majorRoutes);
router.use('/catalog', catalogRoutes);
router.use('/courses', courseRoutes);
router.use('/', materialRoutes);
router.use('/events', eventRoutes);
router.use('/notifications', notificationRoutes);
router.use('/rooms', roomRoutes);
router.use('/invites', inviteRoutes);
router.use('/chat', chatRoutes);
router.use('/ai', aiRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/quiz', quizRoutes);
router.use('/admin', adminRoutes);
router.use('/notes', noteRoutes);
router.use('/resources', resourceRoutes);
router.use('/progress', progressRoutes);
router.use('/community', communityRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/gamification', gamificationRoutes);
router.use('/reports', reportRoutes);

export default router;
