import { Router } from 'express';
import { auth } from '../middleware/auth.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import * as c from '../controllers/noteController.js';
const router = Router();
router.get('/', auth, asyncHandler(c.listNotes));
router.post('/', auth, asyncHandler(c.createNote));
router.put('/:id', auth, asyncHandler(c.updateNote));
router.delete('/:id', auth, asyncHandler(c.deleteNote));
export default router;
