import { Router } from 'express';
import { auth } from '../middleware/auth.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import * as c from '../controllers/notificationController.js';
const router = Router();
router.get('/', auth, asyncHandler(c.listNotifications));
router.put('/read-all', auth, asyncHandler(c.markAllRead));
router.put('/:id/read', auth, asyncHandler(c.markRead));
router.delete('/', auth, asyncHandler(c.clearNotifications));
export default router;
